// Generated by Apple Swift version 4.2 (swiftlang-1000.11.37.1 clang-1000.11.45.1)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if __has_feature(modules)
@import ADSEventLogger;
@import CoreGraphics;
@import Foundation;
@import ObjectiveC;
@import QuartzCore;
@import UIKit;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="ADSFoundation",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif


SWIFT_CLASS("_TtC13ADSFoundation29ADSAccountCenterAuthenticator")
@interface ADSAccountCenterAuthenticator : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_PROTOCOL("_TtP13ADSFoundation10ADSHasName_")
@protocol ADSHasName
@property (nonatomic, readonly, copy) NSString * _Nonnull name;
@end

@class ADSCerebroConfig;

SWIFT_PROTOCOL("_TtP13ADSFoundation12ADSComponent_")
@protocol ADSComponent <ADSHasName>
- (void)open:(ADSCerebroConfig * _Nonnull)config;
- (void)start:(void (^ _Nonnull)(BOOL))done;
- (void)started;
- (void)close;
@end


SWIFT_CLASS("_TtC13ADSFoundation20ADSStandardComponent")
@interface ADSStandardComponent : NSObject <ADSComponent>
@property (nonatomic, readonly, copy) NSString * _Nonnull name;
- (void)open:(ADSCerebroConfig * _Nonnull)config;
- (void)start:(void (^ _Nonnull)(BOOL))done;
- (void)started;
- (void)close;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC13ADSFoundation23ADSAccountDataComponent")
@interface ADSAccountDataComponent : ADSStandardComponent
@end


SWIFT_CLASS("_TtC13ADSFoundation32ADSActiveViewControllerComponent")
@interface ADSActiveViewControllerComponent : ADSStandardComponent
- (void)start:(void (^ _Nonnull)(BOOL))done;
@end


SWIFT_CLASS("_TtC13ADSFoundation27ADSSuccessOrFailureResponse")
@interface ADSSuccessOrFailureResponse : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13ADSFoundation25ADSAddBankAccountResponse")
@interface ADSAddBankAccountResponse : ADSSuccessOrFailureResponse
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UIImage;
@class NSCoder;

SWIFT_CLASS("_TtC13ADSFoundation14ADSAnimatedGIF")
@interface ADSAnimatedGIF : UIImageView
@property (nonatomic, copy) NSString * _Nonnull gifUrlKey;
@property (nonatomic) NSInteger repeatCount;
- (nonnull instancetype)initWithImage:(UIImage * _Nullable)image OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithImage:(UIImage * _Nullable)image highlightedImage:(UIImage * _Nullable)highlightedImage OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13ADSFoundation12ADSApiBridge")
@interface ADSApiBridge : ADSStandardComponent
- (void)open:(ADSCerebroConfig * _Nonnull)config;
- (void)close;
@end


SWIFT_CLASS("_TtC13ADSFoundation21ADSAppUpdateComponent")
@interface ADSAppUpdateComponent : ADSStandardComponent
- (void)open:(ADSCerebroConfig * _Nonnull)config;
@end


SWIFT_CLASS("_TtC13ADSFoundation12ADSImageView")
@interface ADSImageView : UIImageView
@property (nonatomic, copy) NSString * _Nonnull imageUrlKey;
@property (nonatomic, copy) NSString * _Nonnull tintColorKey;
- (nonnull instancetype)initWithImage:(UIImage * _Nullable)image OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithImage:(UIImage * _Nullable)image highlightedImage:(UIImage * _Nullable)highlightedImage OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13ADSFoundation18ADSAvatarImageView")
@interface ADSAvatarImageView : ADSImageView
- (nonnull instancetype)initWithImage:(UIImage * _Nullable)image OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithImage:(UIImage * _Nullable)image highlightedImage:(UIImage * _Nullable)highlightedImage OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13ADSFoundation23ADSBackEndServiceConfig")
@interface ADSBackEndServiceConfig : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC13ADSFoundation25ADSBackgroundingComponent")
@interface ADSBackgroundingComponent : NSObject <ADSComponent>
@property (nonatomic, readonly, copy) NSString * _Nonnull name;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (void)open:(ADSCerebroConfig * _Nonnull)config;
- (void)start:(void (^ _Nonnull)(BOOL))done;
- (void)started;
- (void)close;
@end


SWIFT_CLASS("_TtC13ADSFoundation16ADSBarButtonItem")
@interface ADSBarButtonItem : UIBarButtonItem
@property (nonatomic, copy) NSString * _Nonnull contentKey;
@property (nonatomic, copy) NSString * _Nonnull tintColorKey;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13ADSFoundation22ADSBiometricsComponent")
@interface ADSBiometricsComponent : ADSStandardComponent
@end


SWIFT_CLASS("_TtC13ADSFoundation9ADSButton")
@interface ADSButton : UIButton
@property (nonatomic, copy) NSString * _Nonnull contentKey;
@property (nonatomic, copy) NSString * _Nonnull fontKey;
@property (nonatomic, copy) NSString * _Nonnull fontColorKey;
@property (nonatomic, copy) NSString * _Nonnull fontSelectedColorKey;
@property (nonatomic, copy) NSString * _Nonnull bgColorKey;
@property (nonatomic, copy) NSString * _Nonnull enabledKey;
@property (nonatomic) CGFloat cornerRadius;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class NSBundle;

SWIFT_CLASS("_TtC13ADSFoundation25ADSCarouselViewController")
@interface ADSCarouselViewController : UIViewController
/// Adds the scroll view to the view hierarchy
- (void)awakeFromNib;
/// Calculates the content size and frames based on embedded items and layout mode
- (void)viewDidLayoutSubviews;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class UIScrollView;

@interface ADSCarouselViewController (SWIFT_EXTENSION(ADSFoundation)) <UIScrollViewDelegate>
/// Calls the scroll observer if enabled
/// \param scrollView Scroll view that did scroll
///
- (void)scrollViewDidScroll:(UIScrollView * _Nonnull)scrollView;
/// Calls the scroll observer
/// \param scrollView Scroll view that ended decelerating
///
- (void)scrollViewDidEndDecelerating:(UIScrollView * _Nonnull)scrollView;
@end




SWIFT_CLASS("_TtC13ADSFoundation10ADSCerebro")
@interface ADSCerebro : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC13ADSFoundation16ADSCerebroConfig")
@interface ADSCerebroConfig : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end

@class UIColor;
@class UITouch;
@class UIEvent;

SWIFT_CLASS("_TtC13ADSFoundation11ADSCheckbox")
@interface ADSCheckbox : UIControl
@property (nonatomic, copy) NSString * _Nonnull primaryColorKey;
@property (nonatomic) CGFloat cornerRadius;
@property (nonatomic, strong) UIColor * _Nonnull borderColor;
@property (nonatomic) CGFloat borderWidth;
@property (nonatomic, strong) UIColor * _Nonnull fillColor;
@property (nonatomic, strong) UIColor * _Nonnull checkMarkColor;
@property (nonatomic) CGFloat checkMarkStrokeWidth;
@property (nonatomic) BOOL isChecked;
- (void)prepareForInterfaceBuilder;
- (void)awakeFromNib;
- (void)layoutSubviews;
- (void)endTrackingWithTouch:(UITouch * _Nullable)touch withEvent:(UIEvent * _Nullable)event;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13ADSFoundation7ADSView")
@interface ADSView : UIView
@property (nonatomic, strong) UIColor * _Nonnull shadowColor;
@property (nonatomic) float shadowOpacity;
@property (nonatomic) CGSize shadowOffset;
@property (nonatomic) CGFloat shadowRadius;
@property (nonatomic, copy) NSString * _Nonnull bgColorKey;
@property (nonatomic) CGFloat borderWidth;
@property (nonatomic) CGFloat topBorderWidth;
@property (nonatomic) CGFloat bottomBorderWidth;
@property (nonatomic) CGFloat leftBorderWidth;
@property (nonatomic) CGFloat rightBorderWidth;
@property (nonatomic, copy) NSString * _Nonnull borderColorKey;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13ADSFoundation18ADSCollapsibleView")
@interface ADSCollapsibleView : ADSView
@property (nonatomic, copy) NSString * _Nonnull shouldDisplayKey;
@property (nonatomic, copy) NSString * _Nonnull heightConstraintIdentifier;
@property (nonatomic, copy) NSString * _Nonnull widthConstraintIdentifier;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC13ADSFoundation37ADSConfigurationLoadingViewController")
@interface ADSConfigurationLoadingViewController : UIViewController
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13ADSFoundation23ADSConfigurationRequest")
@interface ADSConfigurationRequest : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC13ADSFoundation24ADSConfigurationResponse")
@interface ADSConfigurationResponse : ADSSuccessOrFailureResponse
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13ADSFoundation20ADSCrashLogComponent")
@interface ADSCrashLogComponent : ADSStandardComponent
- (void)open:(ADSCerebroConfig * _Nonnull)config;
- (void)started;
@end


SWIFT_CLASS("_TtC13ADSFoundation31ADSCreditLimitIncreaseComponent")
@interface ADSCreditLimitIncreaseComponent : ADSStandardComponent
@end


SWIFT_CLASS("_TtC13ADSFoundation30ADSCreditLimitIncreaseResponse")
@interface ADSCreditLimitIncreaseResponse : ADSSuccessOrFailureResponse
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13ADSFoundation12ADSTextField")
@interface ADSTextField : UITextField
@property (nonatomic) BOOL allowPaste;
@property (nonatomic) BOOL allowCut;
@property (nonatomic) BOOL allowCopy;
@property (nonatomic) BOOL allowSelect;
@property (nonatomic) BOOL allowLookup;
@property (nonatomic) BOOL allowShare;
@property (nonatomic) BOOL allowDefine;
@property (nonatomic, copy) NSString * _Nonnull textColorKey;
@property (nonatomic, copy) NSString * _Nonnull placeHolderTextKey;
@property (nonatomic, copy) NSString * _Nonnull placeHolderTextColorKey;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (BOOL)canPerformAction:(SEL _Nonnull)action withSender:(id _Nullable)sender SWIFT_WARN_UNUSED_RESULT;
- (void)textFieldShouldReturn;
@end


SWIFT_CLASS("_TtC13ADSFoundation20ADSCurrencyTextField")
@interface ADSCurrencyTextField : ADSTextField
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)willMoveToSuperview:(UIView * _Null_unspecified)newSuperview;
@end


SWIFT_CLASS("_TtC13ADSFoundation27ADSCustomValidatedTextField")
@interface ADSCustomValidatedTextField : ADSTextField
@property (nonatomic) NSInteger minCharacters;
@property (nonatomic) NSInteger maxCharacters;
@property (nonatomic) BOOL requireNumbers;
@property (nonatomic) BOOL requireCharacters;
@property (nonatomic) BOOL requireAlphanumerics;
@property (nonatomic, copy) NSString * _Nullable regexPattern;
@property (nonatomic) BOOL caseInsensitive;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)truncateStringToMaxCharactersAllowed;
@end


SWIFT_CLASS("_TtC13ADSFoundation17ADSDualCardConfig")
@interface ADSDualCardConfig : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, ADSEnvironment, closed) {
  ADSEnvironmentQa = 0,
  ADSEnvironmentStage = 1,
  ADSEnvironmentProd = 2,
  ADSEnvironmentDev = 3,
};




SWIFT_CLASS("_TtC13ADSFoundation23ADSMessageDataValidator")
@interface ADSMessageDataValidator : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC13ADSFoundation32ADSExceptionMessageDataValidator")
@interface ADSExceptionMessageDataValidator : ADSMessageDataValidator
@end


SWIFT_CLASS("_TtC13ADSFoundation24ADSExtendSessionResponse")
@interface ADSExtendSessionResponse : ADSSuccessOrFailureResponse
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13ADSFoundation16ADSFadeDisplayer")
@interface ADSFadeDisplayer : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC13ADSFoundation24ADSFederatedLinkResponse")
@interface ADSFederatedLinkResponse : ADSSuccessOrFailureResponse
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13ADSFoundation25ADSForgotUsernameResponse")
@interface ADSForgotUsernameResponse : ADSSuccessOrFailureResponse
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13ADSFoundation26ADSGenericSettingComponent")
@interface ADSGenericSettingComponent : ADSStandardComponent
@end


SWIFT_CLASS("_TtC13ADSFoundation25ADSGetAccountDataResponse")
@interface ADSGetAccountDataResponse : ADSSuccessOrFailureResponse
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


typedef SWIFT_ENUM(NSInteger, ADSHostUserState, closed) {
  ADSHostUserStateUntrusted = 0,
  ADSHostUserStateRecognized = 1,
  ADSHostUserStateTrusted = 2,
};


SWIFT_CLASS("_TtC13ADSFoundation16ADSImageRenderer")
@interface ADSImageRenderer : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end



SWIFT_CLASS("_TtC13ADSFoundation8ADSLabel")
@interface ADSLabel : UILabel
@property (nonatomic, copy) NSString * _Nonnull contentKey;
@property (nonatomic, copy) NSString * _Nonnull colorKey;
@property (nonatomic, copy) NSString * _Nonnull selectedColorKey;
@property (nonatomic, copy) NSString * _Nonnull disabledColorKey;
@property (nonatomic, copy) NSString * _Nonnull fontKey;
@property (nonatomic, copy) NSString * _Nonnull enabledKey;
@property (nonatomic) NSInteger htmlFontSize;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13ADSFoundation16ADSLazyImageView")
@interface ADSLazyImageView : ADSImageView
@property (nonatomic, strong) UIImage * _Nullable defaultImage;
@property (nonatomic, strong) UIImage * _Nullable image;
- (void)awakeFromNib;
- (nonnull instancetype)initWithImage:(UIImage * _Nullable)image OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithImage:(UIImage * _Nullable)image highlightedImage:(UIImage * _Nullable)highlightedImage OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13ADSFoundation14ADSLegalFooter")
@interface ADSLegalFooter : ADSView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (void)layoutSubviews;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)legalInfoButtonTapped:(id _Nonnull)sender;
@end

typedef SWIFT_ENUM(NSInteger, ADSLinkStatus, closed) {
  ADSLinkStatusUnlinked = 0,
  ADSLinkStatusLinked = 1,
};


SWIFT_CLASS("_TtC13ADSFoundation15ADSLogComponent")
@interface ADSLogComponent : ADSStandardComponent
- (void)open:(ADSCerebroConfig * _Nonnull)config;
- (void)close;
@end


SWIFT_CLASS("_TtC13ADSFoundation16ADSLoginResponse")
@interface ADSLoginResponse : ADSSuccessOrFailureResponse
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_PROTOCOL("_TtP13ADSFoundation14ADSMessageData_")
@protocol ADSMessageData
@property (nonatomic, readonly, copy) NSString * _Nonnull group;
@property (nonatomic, readonly, copy) NSString * _Nonnull msgKey;
@property (nonatomic, readonly, copy) NSString * _Nonnull senderName;
@property (nonatomic, readonly, copy) NSDictionary<NSString *, id> * _Nonnull data;
- (NSString * _Nonnull)toString SWIFT_WARN_UNUSED_RESULT;
@end



SWIFT_CLASS("_TtC13ADSFoundation17ADSModalDisplayer")
@interface ADSModalDisplayer : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13ADSFoundation22ADSMotivationalMessage")
@interface ADSMotivationalMessage : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC13ADSFoundation17ADSNSTimerAdapter")
@interface ADSNSTimerAdapter : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC13ADSFoundation22ADSNavigationDisplayer")
@interface ADSNavigationDisplayer : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC13ADSFoundation17ADSNavigationItem")
@interface ADSNavigationItem : UINavigationItem
@property (nonatomic, copy) NSString * _Nonnull contentKey;
@property (nonatomic, copy) NSString * _Nonnull titleColorKey;
@property (nonatomic, copy) NSString * _Nonnull tintColorKey;
@property (nonatomic, copy) NSString * _Nonnull leftTitleColorKey;
@property (nonatomic, copy) NSString * _Nonnull leftTintColorKey;
@property (nonatomic, copy) NSString * _Nonnull rightTitleColorKey;
@property (nonatomic, copy) NSString * _Nonnull rightTintColorKey;
@property (nonatomic, copy) NSString * _Nonnull accessibilityIdentifier;
@property (nonatomic, copy) NSString * _Nullable title;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
- (nonnull instancetype)initWithTitle:(NSString * _Nonnull)title SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13ADSFoundation26ADSNavigationItemTitleView")
@interface ADSNavigationItemTitleView : ADSNavigationItem
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13ADSFoundation26ADSNetworkFailurePresenter")
@interface ADSNetworkFailurePresenter : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC13ADSFoundation42ADSOAuthRegistrationRegisterDeviceResponse")
@interface ADSOAuthRegistrationRegisterDeviceResponse : ADSSuccessOrFailureResponse
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13ADSFoundation23ADSOfflineLoginResponse")
@interface ADSOfflineLoginResponse : ADSSuccessOrFailureResponse
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13ADSFoundation14ADSPageControl")
@interface ADSPageControl : UIPageControl
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end




SWIFT_CLASS("_TtC13ADSFoundation7ADSPair")
@interface ADSPair : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end

@protocol ADSUIViewControllerRegistry;
@protocol ADSWorkflowRegistry;

SWIFT_PROTOCOL("_TtP13ADSFoundation9ADSPlugin_")
@protocol ADSPlugin <ADSHasName>
@property (nonatomic, readonly, strong) ADSCerebro * _Nonnull cerebro;
@property (nonatomic, readonly, copy) NSString * _Nonnull name;
@property (nonatomic, readonly, strong) id <ADSUIViewControllerRegistry> _Nullable viewControllerRegistry;
@property (nonatomic, readonly, strong) id <ADSWorkflowRegistry> _Nonnull workflowRegistry;
@end


SWIFT_CLASS("_TtC13ADSFoundation32ADSPreferredStatusBarStyleResult")
@interface ADSPreferredStatusBarStyleResult : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC13ADSFoundation15ADSProgressDial")
@interface ADSProgressDial : UIView
@property (nonatomic) CGFloat percentageComplete;
@property (nonatomic) CGFloat ringSize;
@property (nonatomic, copy) NSString * _Nonnull activatedStateColorKey;
@property (nonatomic, copy) NSString * _Nonnull deactivatedStateColorKey;
@property (nonatomic, strong) UIColor * _Nonnull ringColor;
@property (nonatomic, strong) UIColor * _Nonnull ringBackgroundColor;
@property (nonatomic) double animationDuration;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)prepareForInterfaceBuilder;
@end


SWIFT_CLASS("_TtC13ADSFoundation33ADSRecordAuthFeatureStateResponse")
@interface ADSRecordAuthFeatureStateResponse : ADSSuccessOrFailureResponse
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13ADSFoundation37ADSRegistrationRegisterDeviceResponse")
@interface ADSRegistrationRegisterDeviceResponse : ADSSuccessOrFailureResponse
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13ADSFoundation23ADSRegistrationResponse")
@interface ADSRegistrationResponse : ADSSuccessOrFailureResponse
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13ADSFoundation17ADSRequestFactory")
@interface ADSRequestFactory : ADSStandardComponent
- (void)open:(ADSCerebroConfig * _Nonnull)config;
@end


SWIFT_CLASS("_TtC13ADSFoundation30ADSRequestMessageDataValidator")
@interface ADSRequestMessageDataValidator : ADSMessageDataValidator
@end

typedef SWIFT_ENUM(NSInteger, ADSRequestedFeature, closed) {
  ADSRequestedFeatureHome = 0,
  ADSRequestedFeatureSecureHome = 1,
  ADSRequestedFeatureDigitalCard = 2,
  ADSRequestedFeatureCreditSummary = 3,
  ADSRequestedFeatureTransactionHistory = 4,
  ADSRequestedFeatureRewardsCertificates = 5,
  ADSRequestedFeatureRewardsOverview = 6,
  ADSRequestedFeaturePayBill = 7,
  ADSRequestedFeatureLink = 8,
  ADSRequestedFeatureUnlink = 9,
  ADSRequestedFeaturePaymentOverview = 10,
  ADSRequestedFeatureSettings = 11,
  ADSRequestedFeatureStatements = 12,
  ADSRequestedFeatureRegistration = 13,
  ADSRequestedFeatureDualCard = 14,
  ADSRequestedFeatureCli = 15,
};

typedef SWIFT_ENUM(NSInteger, ADSRequestedSamlReason, closed) {
  ADSRequestedSamlReasonLogin = 0,
  ADSRequestedSamlReasonLink = 1,
};


SWIFT_CLASS("_TtC13ADSFoundation24ADSResetPasswordResponse")
@interface ADSResetPasswordResponse : ADSSuccessOrFailureResponse
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13ADSFoundation31ADSResponseMessageDataValidator")
@interface ADSResponseMessageDataValidator : ADSMessageDataValidator
@end


SWIFT_CLASS("_TtC13ADSFoundation11ADSRetainer")
@interface ADSRetainer : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC13ADSFoundation26ADSRewardsCertificateLabel")
@interface ADSRewardsCertificateLabel : UILabel
@property (nonatomic, copy) NSString * _Nonnull contentKey;
@property (nonatomic, copy) NSString * _Nonnull singularUnitKey;
@property (nonatomic, copy) NSString * _Nonnull pluralUnitKey;
@property (nonatomic, copy) NSString * _Nonnull enabledKey;
@property (nonatomic, copy) NSString * _Nonnull boldColorKey;
@property (nonatomic, copy) NSString * _Nonnull colorKey;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13ADSFoundation29ADSRewardsCertificateResponse")
@interface ADSRewardsCertificateResponse : ADSSuccessOrFailureResponse
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13ADSFoundation30ADSRewardsTransactionsResponse")
@interface ADSRewardsTransactionsResponse : ADSSuccessOrFailureResponse
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13ADSFoundation27ADSScheduledPaymentResponse")
@interface ADSScheduledPaymentResponse : ADSSuccessOrFailureResponse
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13ADSFoundation13ADSScrollView")
@interface ADSScrollView : UIScrollView
@property (nonatomic, copy) NSString * _Nonnull backgroundColorKey;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13ADSFoundation12ADSSearchBar")
@interface ADSSearchBar : UISearchBar
@property (nonatomic, copy) NSString * _Nonnull isSearchBarEnabledKey;
@property (nonatomic, copy) NSString * _Nonnull placeholderBackgroundColorKey;
@property (nonatomic, copy) NSString * _Nonnull placeholderTextColorKey;
@property (nonatomic, copy) NSString * _Nonnull placeholderHintTextKey;
@property (nonatomic, copy) NSString * _Nonnull placeholderHintImageKey;
@property (nonatomic, copy) NSString * _Nonnull placeholderHintTintColorKey;
@property (nonatomic, copy) NSString * _Nonnull searchBarBackgroundColorKey;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13ADSFoundation18ADSStandardContext")
@interface ADSStandardContext : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC13ADSFoundation24ADSSecureWorkflowContext")
@interface ADSSecureWorkflowContext : ADSStandardContext
@end


SWIFT_CLASS("_TtC13ADSFoundation24ADSSendAgreementResponse")
@interface ADSSendAgreementResponse : ADSSuccessOrFailureResponse
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_PROTOCOL("_TtP13ADSFoundation23ControllerRegistryEntry_")
@protocol ControllerRegistryEntry <ADSHasName>
- (UIViewController * _Nonnull)makeController:(ADSCerebro * _Nonnull)cerebro SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC13ADSFoundation30ADSSessionManagementAlertEntry")
@interface ADSSessionManagementAlertEntry : NSObject <ControllerRegistryEntry>
@property (nonatomic, copy) NSString * _Nonnull name;
- (UIViewController * _Nonnull)makeController:(ADSCerebro * _Nonnull)cerebro SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC13ADSFoundation29ADSSessionManagementComponent")
@interface ADSSessionManagementComponent : ADSStandardComponent
- (void)open:(ADSCerebroConfig * _Nonnull)config;
- (void)close;
@end


SWIFT_CLASS("_TtC13ADSFoundation27ADSSessionManagementContext")
@interface ADSSessionManagementContext : ADSStandardContext
@end


SWIFT_CLASS("_TtC13ADSFoundation17ADSStandardPlugin")
@interface ADSStandardPlugin : NSObject <ADSPlugin>
@property (nonatomic, readonly, strong) ADSCerebro * _Nonnull cerebro;
@property (nonatomic, readonly, copy) NSString * _Nonnull name;
@property (nonatomic, strong) id <ADSWorkflowRegistry> _Nonnull workflowRegistry;
@property (nonatomic, readonly, strong) id <ADSUIViewControllerRegistry> _Nullable viewControllerRegistry;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC13ADSFoundation26ADSSessionManagementPlugin")
@interface ADSSessionManagementPlugin : ADSStandardPlugin
@end


SWIFT_CLASS("_TtC13ADSFoundation26ADSSessionManagementResult")
@interface ADSSessionManagementResult : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13ADSFoundation40ADSSessionlessAccountCenterAuthenticator")
@interface ADSSessionlessAccountCenterAuthenticator : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC13ADSFoundation15ADSSettingLabel")
@interface ADSSettingLabel : ADSLabel
@property (nonatomic, copy) NSString * _Nonnull settingEnabledTextKey;
@property (nonatomic, copy) NSString * _Nonnull settingDisabledTextKey;
@property (nonatomic, copy) NSString * _Nonnull settingEnabledColorKey;
@property (nonatomic, copy) NSString * _Nonnull settingDisabledColorKey;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13ADSFoundation20ADSSettingsComponent")
@interface ADSSettingsComponent : ADSStandardComponent
@end


SWIFT_CLASS("_TtC13ADSFoundation23ADSSharedStateComponent")
@interface ADSSharedStateComponent : ADSStandardComponent
- (void)open:(ADSCerebroConfig * _Nonnull)config;
@end


SWIFT_CLASS("_TtC13ADSFoundation12ADSStackView")
@interface ADSStackView : UIStackView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end




SWIFT_CLASS("_TtC13ADSFoundation27ADSStandardNetworkSequencer")
@interface ADSStandardNetworkSequencer : ADSStandardComponent
- (void)start:(void (^ _Nonnull)(BOOL))done;
- (void)close;
/// ADSStandardComponent protocol ‘open’
- (void)open:(ADSCerebroConfig * _Nonnull)config;
@end


@protocol ADSWorkflowDisplayer;
@class ADSWorkflowConnection;
@protocol ADSWorkflow;

SWIFT_PROTOCOL("_TtP13ADSFoundation16ADSWorkflowEntry_")
@protocol ADSWorkflowEntry <ADSHasName>
- (id <ADSWorkflow> _Nonnull)makeWorkflow:(ADSCerebro * _Nonnull)cerebro displayer:(id <ADSWorkflowDisplayer> _Nonnull)displayer connector:(ADSWorkflowConnection * _Nonnull)connector SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC13ADSFoundation24ADSStandardWorkflowEntry")
@interface ADSStandardWorkflowEntry : NSObject <ADSWorkflowEntry>
@property (nonatomic, readonly, copy) NSString * _Nonnull name;
- (id <ADSWorkflow> _Nonnull)makeWorkflow:(ADSCerebro * _Nonnull)cerebro displayer:(id <ADSWorkflowDisplayer> _Nonnull)displayer connector:(ADSWorkflowConnection * _Nonnull)connector SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_PROTOCOL("_TtP13ADSFoundation26ADSWorkflowNavigationToken_")
@protocol ADSWorkflowNavigationToken
@property (nonatomic, readonly, strong) UIViewController * _Nullable controller;
@end


SWIFT_CLASS("_TtC13ADSFoundation34ADSStandardWorkflowNavigationToken")
@interface ADSStandardWorkflowNavigationToken : NSObject <ADSWorkflowNavigationToken>
@property (nonatomic, weak) UIViewController * _Nullable controller;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC13ADSFoundation27ADSStatementContentResponse")
@interface ADSStatementContentResponse : ADSSuccessOrFailureResponse
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13ADSFoundation21ADSStatementsResponse")
@interface ADSStatementsResponse : ADSSuccessOrFailureResponse
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13ADSFoundation17ADSStyleComponent")
@interface ADSStyleComponent : ADSStandardComponent
- (void)open:(ADSCerebroConfig * _Nonnull)config;
- (void)start:(void (^ _Nonnull)(BOOL))done;
- (void)close;
@end



SWIFT_CLASS("_TtC13ADSFoundation9ADSSwitch")
@interface ADSSwitch : UISwitch
@property (nonatomic, copy) NSString * _Nonnull enableTintKey;
@property (nonatomic, copy) NSString * _Nonnull disableTintKey;
@property (nonatomic, copy) NSString * _Nonnull disableBackgroundTintKey;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@protocol ADSWorkflowDelegate;
enum ADSWorkflowDirection : NSInteger;

SWIFT_PROTOCOL("_TtP13ADSFoundation11ADSWorkflow_")
@protocol ADSWorkflow
@property (nonatomic, weak) id <ADSWorkflowDelegate> _Nullable delegate;
- (void)start;
- (void)reset:(id <ADSWorkflowDisplayer> _Nonnull)displayer :(ADSWorkflowConnection * _Nonnull)connector;
@property (nonatomic, strong) ADSWorkflowConnection * _Nonnull connector;
- (void)next:(enum ADSWorkflowDirection)direction;
- (void)setStateTo:(NSString * _Nullable)directState;
@property (nonatomic, readonly, copy) NSString * _Nonnull initialState;
@end

enum ADSWorkflowSynchronizationState : NSInteger;

SWIFT_PROTOCOL("_TtP13ADSFoundation23ADSSynchronizedWorkflow_")
@protocol ADSSynchronizedWorkflow <ADSWorkflow>
@property (nonatomic, readonly, copy) NSString * _Nonnull synchronizationId;
@property (nonatomic) enum ADSWorkflowSynchronizationState synchronizationState;
@property (nonatomic, copy) NSString * _Nullable currentState;
@end


SWIFT_CLASS("_TtC13ADSFoundation12ADSTableView")
@interface ADSTableView : UITableView
@property (nonatomic, copy) NSString * _Nonnull unselectedTextColorKey;
@property (nonatomic, copy) NSString * _Nonnull unselectedBackgroundColorKey;
@property (nonatomic, copy) NSString * _Nonnull selectedTextColorKey;
@property (nonatomic, copy) NSString * _Nonnull selectedBackgroundColorKey;
@property (nonatomic, copy) NSString * _Nonnull separatorColorKey;
@property (nonatomic, copy) NSString * _Nonnull tableBackgroundColorKey;
@property (nonatomic, copy) NSString * _Nonnull accessoryColorKey;
- (nonnull instancetype)initWithFrame:(CGRect)frame style:(UITableViewStyle)style OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13ADSFoundation16ADSTableViewCell")
@interface ADSTableViewCell : UITableViewCell
@property (nonatomic, copy) NSString * _Nonnull backgroundColorKey;
@property (nonatomic) BOOL hideSeparatorInset;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@protocol ADSTappableViewDelegate;

SWIFT_CLASS("_TtC13ADSFoundation15ADSTappableView")
@interface ADSTappableView : ADSView
@property (nonatomic, copy) NSString * _Nonnull tapStateColorKey;
@property (nonatomic, weak) IBOutlet id <ADSTappableViewDelegate> _Nullable delegate;
- (void)touchesBegan:(NSSet<UITouch *> * _Nonnull)touches withEvent:(UIEvent * _Nullable)event;
- (void)touchesCancelled:(NSSet<UITouch *> * _Nonnull)touches withEvent:(UIEvent * _Nullable)event;
- (void)touchesEnded:(NSSet<UITouch *> * _Nonnull)touches withEvent:(UIEvent * _Nullable)event;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_PROTOCOL("_TtP13ADSFoundation23ADSTappableViewDelegate_")
@protocol ADSTappableViewDelegate
- (void)viewWasTapped:(ADSTappableView * _Nonnull)forView;
@end


@class NSTextContainer;

SWIFT_CLASS("_TtC13ADSFoundation11ADSTextView")
@interface ADSTextView : UITextView
@property (nonatomic, copy) NSString * _Nonnull contentKey;
@property (nonatomic, copy) NSString * _Nonnull colorKey;
@property (nonatomic, copy) NSString * _Nonnull tintColorKey;
@property (nonatomic) NSInteger htmlFontSize;
- (nonnull instancetype)initWithFrame:(CGRect)frame textContainer:(NSTextContainer * _Nullable)textContainer OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=7.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13ADSFoundation17ADSTiledIndexPath")
@interface ADSTiledIndexPath : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC13ADSFoundation12ADSTiledView")
@interface ADSTiledView : UIScrollView <ADSTappableViewDelegate>
- (void)awakeFromNib;
- (void)viewWasTapped:(ADSTappableView * _Nonnull)forView;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13ADSFoundation16ADSTiledViewCell")
@interface ADSTiledViewCell : ADSTappableView
- (void)layoutSubviews;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_PROTOCOL("_TtP13ADSFoundation22ADSTiledViewDataSource_")
@protocol ADSTiledViewDataSource
- (NSInteger)maximumTilesForRow SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)numberOfTilesInTiledView SWIFT_WARN_UNUSED_RESULT;
@optional
- (CGFloat)heightForTilesInTiledView SWIFT_WARN_UNUSED_RESULT;
@required
- (ADSTiledViewCell * _Nonnull)tileView:(ADSTiledView * _Nonnull)tileView cellForTileAt:(ADSTiledIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
@optional
- (CGSize)sizeForTileCells SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_PROTOCOL("_TtP13ADSFoundation20ADSTiledViewDelegate_")
@protocol ADSTiledViewDelegate
@optional
- (void)tileView:(ADSTiledView * _Nonnull)tileView didSelectTileAt:(ADSTiledIndexPath * _Nonnull)indexPath;
@end


SWIFT_CLASS("_TtC13ADSFoundation25ADSTouchListenerComponent")
@interface ADSTouchListenerComponent : ADSStandardComponent
- (void)open:(ADSCerebroConfig * _Nonnull)config;
- (void)close;
@end


SWIFT_CLASS("_TtC13ADSFoundation23ADSTransactionsResponse")
@interface ADSTransactionsResponse : ADSSuccessOrFailureResponse
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSURLSession;
@class NSURLAuthenticationChallenge;
@class NSURLCredential;

SWIFT_CLASS("_TtC13ADSFoundation19ADSTrustkitDelegate")
@interface ADSTrustkitDelegate : NSObject <NSURLSessionDelegate>
/// Requests credentials from the delegate in response to a session-level authentication request from the remote server.
/// \param session The session containing the task that requested authentication.
///
/// \param challenge An object that contains the request for authentication.
///
/// \param completionHandler A handler that your delegate method must call
///
- (void)URLSession:(NSURLSession * _Nonnull)session didReceiveChallenge:(NSURLAuthenticationChallenge * _Nonnull)challenge completionHandler:(void (^ _Nonnull)(NSURLSessionAuthChallengeDisposition, NSURLCredential * _Nullable))completionHandler;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC13ADSFoundation26ADSTwoTabsSegmentedControl")
@interface ADSTwoTabsSegmentedControl : UISegmentedControl
@property (nonatomic, copy) NSString * _Nonnull colorKey;
@property (nonatomic, copy) NSString * _Nonnull backgroundColorKey;
@property (nonatomic, copy) NSString * _Nonnull firstContentKey;
@property (nonatomic, copy) NSString * _Nonnull secondContentKey;
@property (nonatomic, copy) NSString * _Nonnull isEnabledKey;
- (nonnull instancetype)initWithItems:(NSArray * _Nullable)items OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13ADSFoundation20ADSUIRouterComponent")
@interface ADSUIRouterComponent : ADSStandardComponent
- (void)open:(ADSCerebroConfig * _Nonnull)config;
@end


SWIFT_PROTOCOL("_TtP13ADSFoundation27ADSUIViewControllerRegistry_")
@protocol ADSUIViewControllerRegistry
- (UIViewController * _Nullable)getViewController:(NSString * _Nonnull)name SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC13ADSFoundation28ADSUnderlineSegmentedControl")
@interface ADSUnderlineSegmentedControl : UISegmentedControl
@property (nonatomic, copy) NSString * _Nonnull colorKey;
@property (nonatomic, copy) NSString * _Nonnull backgroundColorKey;
@property (nonatomic, copy) NSString * _Nonnull firstContentKey;
@property (nonatomic, copy) NSString * _Nonnull secondContentKey;
@property (nonatomic, copy) NSString * _Nonnull thirdContentKey;
@property (nonatomic) CGFloat tabUnderlineHeight;
@property (nonatomic) NSTimeInterval tabUnderlineAnimationTime;
- (void)awakeFromNib;
- (nonnull instancetype)initWithItems:(NSArray * _Nullable)items OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end




SWIFT_CLASS("_TtC13ADSFoundation17ADSUntypedRequest")
@interface ADSUntypedRequest : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC13ADSFoundation18ADSUntypedResponse")
@interface ADSUntypedResponse : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC13ADSFoundation21ADSValidatedTextField")
@interface ADSValidatedTextField : ADSTextField
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)truncateStringToMaxCharactersAllowed;
@end


SWIFT_CLASS("_TtC13ADSFoundation35ADSVerifyIdentificationCodeResponse")
@interface ADSVerifyIdentificationCodeResponse : ADSSuccessOrFailureResponse
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC13ADSFoundation10ADSWebView")
@interface ADSWebView : UIWebView
@property (nonatomic, copy) NSString * _Nonnull htmlContentKey;
@property (nonatomic, copy) NSString * _Nonnull htmlStylesKey;
@property (nonatomic, copy) NSString * _Nonnull urlContentKey;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13ADSFoundation22ADSWebViewPluginExpert")
@interface ADSWebViewPluginExpert : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC13ADSFoundation23ADSWorkflowActivityKeys")
@interface ADSWorkflowActivityKeys : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13ADSFoundation21ADSWorkflowConnection")
@interface ADSWorkflowConnection : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_PROTOCOL("_TtP13ADSFoundation19ADSWorkflowDelegate_")
@protocol ADSWorkflowDelegate
- (void)workflowStateChangedOn:(id <ADSWorkflow> _Nonnull)workflow withState:(NSString * _Nullable)state;
- (void)workflowFinishedOn:(id <ADSWorkflow> _Nonnull)workflow withResult:(NSInteger)result;
- (void)workflowDeinitializedOn:(id <ADSWorkflow> _Nonnull)workflow;
@end

typedef SWIFT_ENUM(NSInteger, ADSWorkflowDirection, closed) {
  ADSWorkflowDirectionForward = 0,
  ADSWorkflowDirectionBackward = 1,
  ADSWorkflowDirectionDone = 2,
  ADSWorkflowDirectionDirect = 3,
};

@class CATransition;
@class UIAlertAction;

SWIFT_PROTOCOL("_TtP13ADSFoundation20ADSWorkflowDisplayer_")
@protocol ADSWorkflowDisplayer
- (id <ADSWorkflowNavigationToken> _Nullable)record SWIFT_WARN_UNUSED_RESULT;
- (void)display:(UIViewController * _Nonnull)controller transition:(CATransition * _Nullable)transition;
- (void)dismissTo:(UIViewController * _Nonnull)controller transition:(CATransition * _Nullable)transition;
- (void)dismiss:(BOOL)animated;
- (void)dismissToToken:(id <ADSWorkflowNavigationToken> _Nonnull)token animated:(BOOL)animated;
- (void)executeDismissHandler;
- (BOOL)contains:(UIViewController * _Nonnull)controller SWIFT_WARN_UNUSED_RESULT;
- (void)displayStandardAlertWithTitle:(NSString * _Nonnull)title message:(NSString * _Nonnull)message alertAction:(void (^ _Nullable)(UIAlertAction * _Nonnull))alertAction presentCompletion:(void (^ _Nullable)(void))presentCompletion;
- (void)displayStandardAlertWithTitle:(NSString * _Nullable)title andMessage:(NSString * _Nullable)message buttonText:(NSString * _Nullable)buttonText alertAction:(void (^ _Nullable)(UIAlertAction * _Nonnull))alertAction presentCompletion:(void (^ _Nullable)(void))presentCompletion;
- (void)displayAlertWithTitle:(NSString * _Nonnull)title andMessage:(NSString * _Nonnull)message uiAlertActions:(NSArray<UIAlertAction *> * _Nonnull)uiAlertActions presentCompletion:(void (^ _Nullable)(void))presentCompletion;
- (void)block;
- (void)unblock;
- (void)blockNav;
- (void)unblockNav;
- (void)showCancelButtonWithTitle:(NSString * _Nonnull)title andColor:(UIColor * _Nonnull)color andTarget:(NSObject * _Nonnull)target andAction:(SEL _Nonnull)action;
- (void)hideCancelButton;
- (void)showMessage:(NSString * _Nonnull)message withFontColor:(UIColor * _Nonnull)color;
@property (nonatomic, strong) CATransition * _Nullable lastTransitionTo;
@end



SWIFT_CLASS("_TtC13ADSFoundation30ADSWorkflowNavigationDisplayer")
@interface ADSWorkflowNavigationDisplayer : NSObject <ADSWorkflowDisplayer>
@property (nonatomic, strong) CATransition * _Nullable lastTransitionTo;
- (id <ADSWorkflowNavigationToken> _Nullable)record SWIFT_WARN_UNUSED_RESULT;
- (void)display:(UIViewController * _Nonnull)controller transition:(CATransition * _Nullable)transition;
- (void)dismissTo:(UIViewController * _Nonnull)controller transition:(CATransition * _Nullable)transition;
- (void)dismissToToken:(id <ADSWorkflowNavigationToken> _Nonnull)token animated:(BOOL)animated;
- (void)dismiss:(BOOL)animated;
- (void)executeDismissHandler;
- (BOOL)contains:(UIViewController * _Nonnull)controller SWIFT_WARN_UNUSED_RESULT;
- (void)displayStandardAlertWithTitle:(NSString * _Nonnull)title message:(NSString * _Nonnull)message alertAction:(void (^ _Nullable)(UIAlertAction * _Nonnull))alertAction presentCompletion:(void (^ _Nullable)(void))presentCompletion;
- (void)displayStandardAlertWithTitle:(NSString * _Nullable)title andMessage:(NSString * _Nullable)message buttonText:(NSString * _Nullable)buttonText alertAction:(void (^ _Nullable)(UIAlertAction * _Nonnull))alertAction presentCompletion:(void (^ _Nullable)(void))presentCompletion;
- (void)displayAlertWithTitle:(NSString * _Nonnull)title andMessage:(NSString * _Nonnull)message uiAlertActions:(NSArray<UIAlertAction *> * _Nonnull)uiAlertActions presentCompletion:(void (^ _Nullable)(void))presentCompletion;
- (void)block;
- (void)blockNav;
- (void)unblock;
- (void)unblockNav;
- (void)showCancelButtonWithTitle:(NSString * _Nonnull)title andColor:(UIColor * _Nonnull)color andTarget:(NSObject * _Nonnull)target andAction:(SEL _Nonnull)action;
- (void)hideCancelButton;
- (void)showMessage:(NSString * _Nonnull)message withFontColor:(UIColor * _Nonnull)fontColor;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end



SWIFT_PROTOCOL("_TtP13ADSFoundation19ADSWorkflowRegistry_")
@protocol ADSWorkflowRegistry
- (id <ADSWorkflow> _Nullable)makeWorkflow:(NSString * _Nonnull)name displayer:(id <ADSWorkflowDisplayer> _Nonnull)displayer connector:(ADSWorkflowConnection * _Nonnull)connector SWIFT_WARN_UNUSED_RESULT;
- (BOOL)contains:(NSString * _Nonnull)name SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC13ADSFoundation17ADSWorkflowRouter")
@interface ADSWorkflowRouter : ADSStandardComponent <ADSWorkflowDelegate>
- (void)open:(ADSCerebroConfig * _Nonnull)config;
- (void)workflowStateChangedOn:(id <ADSWorkflow> _Nonnull)workflow withState:(NSString * _Nullable)state;
- (void)workflowFinishedOn:(id <ADSWorkflow> _Nonnull)workflow withResult:(NSInteger)result;
- (void)workflowDeinitializedOn:(id <ADSWorkflow> _Nonnull)workflow;
@end

typedef SWIFT_ENUM(NSInteger, ADSWorkflowSynchronizationState, closed) {
  ADSWorkflowSynchronizationStateSynchronizing = 0,
  ADSWorkflowSynchronizationStateWaitingToSynchronize = 1,
};










@class UIResponder;

@interface UIApplication (SWIFT_EXTENSION(ADSFoundation))
@property (nonatomic, readonly, strong) UIResponder * _Nullable nextResponder;
@end
















@interface UINavigationController (SWIFT_EXTENSION(ADSFoundation))
@property (nonatomic, readonly) UIStatusBarStyle preferredStatusBarStyle;
@end















#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
