// Generated by Apple Swift version 4.1.2 effective-3.3.2 (swiftlang-902.0.54 clang-902.0.39.2)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR __attribute__((enum_extensibility(open)))
# else
#  define SWIFT_ENUM_ATTR
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name) enum _name : _type _name; enum SWIFT_ENUM_ATTR SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) SWIFT_ENUM(_type, _name)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if __has_feature(modules)
@import ADSFoundation;
@import UIKit;
@import Foundation;
@import CoreGraphics;
@import QuartzCore;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="ADSACKit",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

@class ADSCerebro;
@class ADSStandardWorkflowEntry;
@protocol ADSUIViewControllerRegistry;

SWIFT_CLASS("_TtC8ADSACKit14ADSACKitPlugin")
@interface ADSACKitPlugin : ADSStandardPlugin
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull PluginName;)
+ (NSString * _Nonnull)PluginName SWIFT_WARN_UNUSED_RESULT;
+ (void)setPluginName:(NSString * _Nonnull)value;
- (nonnull instancetype)initWithCerebro:(ADSCerebro * _Nonnull)cerebro OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCerebro:(ADSCerebro * _Nonnull)cerebro name:(NSString * _Nonnull)name workflowEntries:(NSArray<ADSStandardWorkflowEntry *> * _Nonnull)workflowEntries viewControllerRegistry:(id <ADSUIViewControllerRegistry> _Nullable)viewControllerRegistry SWIFT_UNAVAILABLE;
@end

@class ADSRetainer;
@class UIStoryboardSegue;
@class NSBundle;
@class NSCoder;

SWIFT_CLASS("_TtC8ADSACKit27ADSAddAccountViewController")
@interface ADSAddAccountViewController : UIViewController
@property (nonatomic, strong) ADSRetainer * _Nullable retainer;
@property (nonatomic) BOOL _hideBackButton;
@property (nonatomic, copy) NSString * _Nullable analyticPageName;
@property (nonatomic, copy) NSString * _Nullable descriptivePageName;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (void)prepareForSegue:(UIStoryboardSegue * _Nonnull)segue sender:(id _Nullable)sender;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@protocol ADSWorkflowDisplayer;

SWIFT_CLASS("_TtC8ADSACKit24ADSAuthenticationContext")
@interface ADSAuthenticationContext : ADSStandardContext
@property (nonatomic) BOOL outOfBand;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nullable loginResponse;
@property (nonatomic) BOOL eulaAccepted;
@property (nonatomic, copy) NSString * _Nullable username;
@property (nonatomic) BOOL fromLinkNag;
@property (nonatomic) BOOL shouldGoToMVC;
@property (nonatomic, copy) NSString * _Nullable loginReturnCode;
@property (nonatomic, copy) NSString * _Nonnull saml;
@property (nonatomic, copy) NSString * _Nonnull token;
- (void)fromDictionary:(NSDictionary<NSString *, id> * _Nonnull)data;
- (nonnull instancetype)init:(ADSCerebro * _Nonnull)cerebro :(id <ADSWorkflowDisplayer> _Nullable)displayer OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8ADSACKit27ADSBankAccountTableViewCell")
@interface ADSBankAccountTableViewCell : UITableViewCell
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class UITableView;

SWIFT_CLASS("_TtC8ADSACKit28ADSBankAccountViewController")
@interface ADSBankAccountViewController : UIViewController <UITableViewDataSource, UITableViewDelegate>
@property (nonatomic, copy) NSString * _Nullable analyticPageName;
@property (nonatomic, copy) NSString * _Nullable descriptivePageName;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (IBAction)addAccount:(id _Nonnull)sender;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8ADSACKit20ADSBiometricsContext")
@interface ADSBiometricsContext : ADSSecureWorkflowContext
- (nonnull instancetype)init:(ADSCerebro * _Nonnull)cerebro :(id <ADSWorkflowDisplayer> _Nullable)displayer OBJC_DESIGNATED_INITIALIZER;
@end

@class UIColor;
@class UIImage;

SWIFT_CLASS("_TtC8ADSACKit16ADSCardImageView")
@interface ADSCardImageView : ADSImageView
@property (nonatomic, strong) UIColor * _Nonnull shadowColor;
@property (nonatomic) float shadowOpacity;
@property (nonatomic) CGSize shadowOffset;
@property (nonatomic) CGFloat shadowRadius;
@property (nonatomic, strong) UIImage * _Nullable image;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)decoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (void)updateImageKeyWithPrefix:(NSString * _Nullable)prefix postfix:(NSString * _Nullable)postfix;
- (nonnull instancetype)initWithImage:(UIImage * _Nullable)image SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithImage:(UIImage * _Nullable)image highlightedImage:(UIImage * _Nullable)highlightedImage SWIFT_UNAVAILABLE;
@end

@class CAAnimation;

SWIFT_CLASS("_TtC8ADSACKit12ADSCheckmark")
@interface ADSCheckmark : UIView <CAAnimationDelegate>
@property (nonatomic, copy) NSString * _Nonnull circleColorKey;
@property (nonatomic, strong) UIColor * _Nonnull circleColor;
@property (nonatomic, strong) UIColor * _Nonnull checkmarkColor;
@property (nonatomic) double animationDuration;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, copy) NSString * _Nonnull configurableType;
- (NSArray<NSString *> * _Nonnull)getAllStyleKeys SWIFT_WARN_UNUSED_RESULT;
- (NSArray<NSString *> * _Nonnull)getAllContentKeys SWIFT_WARN_UNUSED_RESULT;
- (NSArray<NSString *> * _Nonnull)getAllFunctionalKeys SWIFT_WARN_UNUSED_RESULT;
- (void)applyStyling:(NSDictionary<NSString *, id> * _Nonnull)styles;
- (void)applyContent:(NSDictionary<NSString *, id> * _Nonnull)content;
- (void)applyFunctional:(NSDictionary<NSString *, id> * _Nonnull)functional;
- (void)startAnimation;
- (void)animationDidStop:(CAAnimation * _Nonnull)anim finished:(BOOL)flag;
@end


SWIFT_CLASS("_TtC8ADSACKit36ADSFirstTimeAddAccountViewController")
@interface ADSFirstTimeAddAccountViewController : ADSAddAccountViewController
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class ADSAccountDataComponent;

SWIFT_CLASS("_TtC8ADSACKit24ADSForgotUsernameContext")
@interface ADSForgotUsernameContext : ADSStandardContext
@property (nonatomic, copy) NSString * _Nullable username;
@property (nonatomic, copy) NSString * _Nullable passwordResetToken;
@property (nonatomic) BOOL isFullyAuthenticated;
@property (nonatomic) BOOL eulaAccepted;
@property (nonatomic, readonly) BOOL fromLink;
@property (nonatomic, copy) NSString * _Nullable verificationMethodDisplayValue;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nullable loginResponse;
@property (nonatomic, strong) ADSAccountDataComponent * _Nullable accountDataComponent;
- (nonnull instancetype)init:(ADSCerebro * _Nonnull)cerebro :(id <ADSWorkflowDisplayer> _Nullable)displayer OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8ADSACKit10ADSInfoBar")
@interface ADSInfoBar : ADSView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class ADSCerebroConfig;

SWIFT_CLASS("_TtC8ADSACKit38ADSMobileVirtualCardAccessLogComponent")
@interface ADSMobileVirtualCardAccessLogComponent : ADSStandardComponent
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull MESSAGE_GROUP;)
+ (NSString * _Nonnull)MESSAGE_GROUP SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull MESSAGE_KEY;)
+ (NSString * _Nonnull)MESSAGE_KEY SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull LISTENER_KEY;)
+ (NSString * _Nonnull)LISTENER_KEY SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithCerebro:(ADSCerebro * _Nonnull)cerebro OBJC_DESIGNATED_INITIALIZER;
- (void)open:(ADSCerebroConfig * _Nonnull)config;
@end


SWIFT_CLASS("_TtC8ADSACKit34ADSMobileVirtualCardViewController")
@interface ADSMobileVirtualCardViewController : UIViewController
@property (nonatomic, copy) NSString * _Nullable descriptivePageName;
@property (nonatomic, readonly, copy) NSString * _Nullable analyticPageName;
@property (nonatomic, strong) ADSRetainer * _Nullable retainer;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewDidAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class UITextField;

SWIFT_CLASS("_TtC8ADSACKit28ADSOtherAmountViewController")
@interface ADSOtherAmountViewController : UIViewController <UITableViewDataSource, UITableViewDelegate, UITextFieldDelegate>
@property (nonatomic, copy) NSString * _Nullable analyticPageName;
@property (nonatomic, copy) NSString * _Nullable descriptivePageName;
- (void)back;
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)animated;
- (BOOL)shouldPerformSegueWithIdentifier:(NSString * _Nonnull)withIdentifier sender:(id _Nullable)sender SWIFT_WARN_UNUSED_RESULT;
- (void)prepareForSegue:(UIStoryboardSegue * _Nonnull)segue sender:(id _Nullable)sender;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (BOOL)textField:(UITextField * _Nonnull)textField shouldChangeCharactersInRange:(NSRange)range replacementString:(NSString * _Nonnull)string SWIFT_WARN_UNUSED_RESULT;
- (void)textFieldDidEndEditing:(UITextField * _Nonnull)textField;
- (BOOL)textFieldShouldClear:(UITextField * _Nonnull)textField SWIFT_WARN_UNUSED_RESULT;
- (BOOL)textFieldShouldReturn:(UITextField * _Nonnull)textField SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8ADSACKit19ADSOutOfBandContext")
@interface ADSOutOfBandContext : ADSStandardContext
- (nonnull instancetype)init:(ADSCerebro * _Nonnull)cerebro :(id <ADSWorkflowDisplayer> _Nullable)displayer OBJC_DESIGNATED_INITIALIZER;
- (void)closeSession;
- (void)extendSession;
- (void)fromDictionary:(NSDictionary<NSString *, id> * _Nonnull)data;
@end


SWIFT_CLASS("_TtC8ADSACKit26ADSOutOfBandViewController")
@interface ADSOutOfBandViewController : UIViewController <UITableViewDataSource, UITableViewDelegate>
@property (nonatomic, strong) ADSRetainer * _Nullable retainer;
@property (nonatomic, copy) NSString * _Nullable analyticPageName;
@property (nonatomic, copy) NSString * _Nullable descriptivePageName;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewDidAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (BOOL)tableView:(UITableView * _Nonnull)tableView canEditRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8ADSACKit30ADSPaymentAmountViewController")
@interface ADSPaymentAmountViewController : UIViewController <UITableViewDataSource, UITableViewDelegate>
@property (nonatomic, copy) NSString * _Nullable analyticPageName;
@property (nonatomic, copy) NSString * _Nullable descriptivePageName;
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)animated;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)back;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@protocol ADSWorkflowNavigationToken;

SWIFT_CLASS("_TtC8ADSACKit17ADSPaymentContext")
@interface ADSPaymentContext : ADSSecureWorkflowContext
@property (nonatomic, readonly, strong) id <ADSWorkflowNavigationToken> _Nullable navigationToken;
@property (nonatomic, strong) ADSAccountDataComponent * _Nullable accountDataComponent;
- (void)fromDictionary:(NSDictionary<NSString *, id> * _Nonnull)data;
- (void)invalidateScheduledPaymentCache;
- (nonnull instancetype)init:(ADSCerebro * _Nonnull)cerebro :(id <ADSWorkflowDisplayer> _Nullable)displayer OBJC_DESIGNATED_INITIALIZER;
@end

@class UIButton;

SWIFT_CLASS("_TtC8ADSACKit32ADSPaymentOverviewViewController")
@interface ADSPaymentOverviewViewController : UIViewController <UITableViewDataSource, UITableViewDelegate>
@property (nonatomic, copy) NSString * _Nullable descriptivePageName;
@property (nonatomic, copy) NSString * _Nullable analyticPageName;
@property (nonatomic, strong) ADSRetainer * _Nullable retainer;
@property (nonatomic) BOOL _hideBackButton;
@property (nonatomic) BOOL scheduledWebServiceGetCalled;
@property (nonatomic) BOOL completedWebServiceGetCalled;
@property (nonatomic) BOOL paymentServiceCompleted;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (NSInteger)numberOfSectionsInTableView:(UITableView * _Nonnull)tableView SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)tableView:(UITableView * _Nonnull)tableView titleForHeaderInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForHeaderInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForFooterInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
/// Navigate to Cntainer View ADSPaymentDetailContainerViewController
/// \param segue segue
///
/// \param sender sender object
///
- (void)prepareForSegue:(UIStoryboardSegue * _Nonnull)segue sender:(id _Nullable)sender;
- (void)callPaymentWebServiceAgainWithButton:(UIButton * _Nonnull)button;
@end


SWIFT_CLASS("_TtC8ADSACKit18ADSProgressStepper")
@interface ADSProgressStepper : UIView
@property (nonatomic, copy) NSString * _Nonnull activatedStateColorKey;
@property (nonatomic, copy) NSString * _Nonnull deactivatedStateColorKey;
@property (nonatomic) NSInteger numberOfStates;
@property (nonatomic, strong) UIColor * _Nonnull activatedColor;
@property (nonatomic, strong) UIColor * _Nonnull deactivatedColor;
@property (nonatomic) CGFloat marginX;
@property (nonatomic) CGFloat marginY;
@property (nonatomic, readonly) CGFloat circleDiameter;
@property (nonatomic, readonly) CGFloat circleRadius;
@property (nonatomic, readonly) CGFloat lineDistance;
@property (nonatomic, readonly) CGFloat lineHeight;
@property (nonatomic, readonly) CGFloat circleBorderWidth;
@property (nonatomic, readonly) CGFloat textSize;
@property (nonatomic, readonly) CGFloat leftMargin;
@property (nonatomic, readonly) CGFloat topMargin;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, copy) NSString * _Nonnull configurableType;
- (NSArray<NSString *> * _Nonnull)getAllStyleKeys SWIFT_WARN_UNUSED_RESULT;
- (NSArray<NSString *> * _Nonnull)getAllContentKeys SWIFT_WARN_UNUSED_RESULT;
- (NSArray<NSString *> * _Nonnull)getAllFunctionalKeys SWIFT_WARN_UNUSED_RESULT;
- (void)applyConfigurationWithStyles:(NSDictionary<NSString *, id> * _Nonnull)styles content:(NSDictionary<NSString *, id> * _Nonnull)content functional:(NSDictionary<NSString *, id> * _Nonnull)functional;
- (void)applyContent:(NSDictionary<NSString *, id> * _Nonnull)content;
- (void)applyFunctional:(NSDictionary<NSString *, id> * _Nonnull)functional;
- (void)applyStyling:(NSDictionary<NSString *, id> * _Nonnull)styles;
- (void)drawRect:(CGRect)rect;
@end


SWIFT_CLASS("_TtC8ADSACKit22ADSRegistrationContext")
@interface ADSRegistrationContext : ADSStandardContext
@property (nonatomic, readonly, copy) NSString * _Nonnull backendService;
@property (nonatomic) BOOL returnToSignin;
@property (nonatomic) BOOL eulaAccepted;
@property (nonatomic) BOOL paperlessEulaAccepted;
@property (nonatomic) BOOL dontKnowAccountNumberEnabled;
- (nonnull instancetype)init:(ADSCerebro * _Nonnull)cerebro :(id <ADSWorkflowDisplayer> _Nullable)displayer OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8ADSACKit25ADSRegistrationController")
@interface ADSRegistrationController : UIViewController
@property (nonatomic, strong) ADSRetainer * _Nullable retainer;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8ADSACKit48ADSRegistrationEnterAccountDetailsViewController")
@interface ADSRegistrationEnterAccountDetailsViewController : ADSRegistrationController
@property (nonatomic, copy) NSString * _Nullable analyticPageName;
@property (nonatomic, copy) NSString * _Nullable descriptivePageName;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
- (void)prepareForSegue:(UIStoryboardSegue * _Nonnull)segue sender:(id _Nullable)sender;
- (void)hideKeyboard;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class ADSGetAccountDataResponse;
@class NSError;

SWIFT_CLASS("_TtC8ADSACKit22ADSRegistrationManager")
@interface ADSRegistrationManager : ADSStandardComponent
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nullable registrationDictionary;
- (void)createAccountInBackendWithUsernameWithContext:(ADSRegistrationContext * _Nonnull)context username:(NSString * _Nonnull)username password:(NSString * _Nonnull)password email:(NSString * _Nonnull)email mobilePhone:(NSString * _Nullable)mobilePhone deviceIdentifier:(NSString * _Nonnull)deviceIdentifier getAccountData:(void (^ _Nonnull)(void (^ _Nonnull)(ADSGetAccountDataResponse * _Nullable)))getAccountData successHandler:(void (^ _Nonnull)(BOOL, NSString * _Nullable))successHandler failureHandler:(void (^ _Nonnull)(NSString * _Nonnull, NSError * _Nullable))failureHandler;
- (void)validateAccountFromBackendWithContext:(ADSRegistrationContext * _Nonnull)context accountIdentifier:(NSString * _Nonnull)accountIdentifier idType:(NSString * _Nonnull)idType idValue:(NSString * _Nonnull)idValue zipCode:(NSString * _Nonnull)zipCode successHandler:(void (^ _Nonnull)(void))successHandler failureHandler:(void (^ _Nonnull)(NSString * _Nullable, NSError * _Nullable))failureHandler;
- (nonnull instancetype)initWithCerebro:(ADSCerebro * _Nonnull)cerebro OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8ADSACKit29ADSRegistrationViewController")
@interface ADSRegistrationViewController : ADSRegistrationController
@property (nonatomic, copy) NSString * _Nullable analyticPageName;
@property (nonatomic, copy) NSString * _Nullable descriptivePageName;
- (void)viewDidLoad;
- (void)prepareForSegue:(UIStoryboardSegue * _Nonnull)segue sender:(id _Nullable)sender;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8ADSACKit31ADSSecureHomeBaseViewController")
@interface ADSSecureHomeBaseViewController : UIViewController
@property (nonatomic, copy) NSString * _Nullable descriptivePageName;
@property (nonatomic, readonly, copy) NSString * _Nullable analyticPageName;
- (void)viewDidLoad;
- (void)viewWillDisappear:(BOOL)animated;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class UIScrollView;

SWIFT_CLASS("_TtC8ADSACKit41ADSSecureHomeAccountSummaryViewController")
@interface ADSSecureHomeAccountSummaryViewController : ADSSecureHomeBaseViewController <UITableViewDataSource, UITableViewDelegate>
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewDidAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)scrollViewDidScroll:(UIScrollView * _Nonnull)scrollView;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC8ADSACKit27ADSSecureHomeViewController")
@interface ADSSecureHomeViewController : ADSSecureHomeBaseViewController
@property (nonatomic, strong) ADSRetainer * _Nullable retainer;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
- (void)viewDidAppear:(BOOL)animated;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8ADSACKit17ADSShowHideButton")
@interface ADSShowHideButton : ADSButton
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8ADSACKit17ADSWelcomeContext")
@interface ADSWelcomeContext : ADSStandardContext
@property (nonatomic) BOOL userHasLoggedInOnce;
- (void)fromDictionary:(NSDictionary<NSString *, id> * _Nonnull)data;
- (nonnull instancetype)init:(ADSCerebro * _Nonnull)cerebro :(id <ADSWorkflowDisplayer> _Nullable)displayer OBJC_DESIGNATED_INITIALIZER;
@end





#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
